import test from 'ava'

test.todo('close() removes file watcher')
test.todo('close() removes temp directory')
test.todo('importAsset() copies file to temp directory')
test.todo('importAsset() returns a relative path')
test.todo('setDocument() sets the window title')
test.todo('setDocument() adds file to recent files')
test.todo('open()')
test.todo('readData()')
test.todo('save()')
test.todo('store()')
test.todo('watch()')
test.todo('addRecentDocument()')
test.todo('removeRecentDocument()')
