name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: "release"
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos, windows]
    runs-on: ${{ matrix.os }}-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: npm
      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            dist
          key: ${{ runner.os }}-electron-build-${{ hashFiles('dist') }}
          restore-keys: |
            ${{ runner.os }}-electron-build-
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
        env:
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WORDS_API_KEY: ${{ secrets.WORDS_API_KEY }}
